spring.application.name=TodoVite
spring.datasource.url=jdbc:postgresql://localhost:5432/tododb
spring.datasource.username=sa
spring.datasource.password=Yunkhngn123!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.docker.compose.enabled=false
